# Generated by Django 5.1.5 on 2025-03-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todolist_delete_todo_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='created_at',
        ),
    ]
