# Generated by Django 5.1.5 on 2025-04-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_todolist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
