# Generated by Django 5.1.5 on 2025-04-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_todohistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoHistory',
        ),
    ]
